version: '3.4'
services:
  bitbucket:
    # image: mrleloi/bitbucket:8.9.8
    image: atlassian/bitbucket:8.9.8
    container_name: bitbucket-srv
    environment:
      - TZ=Asia/Ho_Chi_Minh
#      - JVM_MINIMUM_MEMORY=1g
#      - JVM_MAXIMUM_MEMORY=12g
#      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - postgres
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - home_data:/var/bitbucket
      - ./atlassian-agent.jar:/atlassian-agent.jar:ro
      - ./atlassian-extras-3.4.6.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/atlassian-extras-3.4.6.jar:ro
    restart: always
    networks:
      - network-bridge

  postgres:
      image: postgres:latest
      container_name: bitbucket-postgressql
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_DB: bitbucket
        POSTGRES_USER: bitbucket
        POSTGRES_PASSWORD: 123123
      volumes:
        - postgres_data:/var/lib/postgresql/data/pgdata
      restart: always
      networks:
        - network-bridge

#   mysql:
#     image: mysql:8
#     container_name: mysql-bitbucket
#     environment:
#       - TZ=Asia/Ho_Chi_Minh
#       - MYSQL_DATABASE=bitbucket
#       - MYSQL_ROOT_PASSWORD=123456
#       - MYSQL_USER=bitbucket
#       - MYSQL_PASSWORD=123123
#     command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
# #    ports:
# #      - "13306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     restart: always
#     networks:
#       - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
#   mysql_data:
#     external: false
  postgres_data:
   external: false
